### PR TITLE
Add SPT TestRunner for Eclipse to the Spoofax features.

### PR DESCRIPTION
**Pull request by VolkerL**
The SPT testrunner for Eclipse is now in a useable state.
It still needs many extra features but for now it is at least useable.

Invoke it via `Right Click on a project -> Spoofax -> Run All SPT Tests`.

### CODE REVIEW

**Comment by Gohla** [comment]
You shouldn't add the testrunner to both the non-meta and meta features. The test runner is a meta-feature, since it concerns language development, so it should only be added to the meta-feature. It should also be plugged into the 'Spoofax (meta)' menu for that reason.

**Comment by VolkerL** [comment]
I'm trying to get the following behaviour:

If you have an open SPT file and click on the `Spoofax (meta)` menu bar entry, you can select `Run SPT tests`.
It then gets the open editor input through `HandlerUtil.getActiveEditorInput`.
I should be able to resolve that to a VFS file with the `IEclipseResourceService`.
Then I can run the tests of that file

The `IEclipseResourceService` seems to be private. So how should I go about doing this?

**Comment by VolkerL** [comment]
I removed it from the normal Spoofax, and left it only in `org.metaborg.spoofax.eclipse.meta.feature`.

For some reason locally my build passes, but the updatesite project has `org.metaborg.spt.testrunner.eclipse.2.1.0.qualifier.jar` instead of replacing that `qualifier` with a timestamp.
I had the same type of problem on April 12th when trying to add `spt.core`.
It magically started working locally again after it got into the main repo, so I don't know what's causing it, but it shouldn't be a problem.

The build passes locally, so it should be safe to merge.

**Comment by VolkerL** [comment]
I moved from the downloaded Eclipse with preinstalled stuff to a new Eclipse Neon instance and installed from my local Spoofax update site.
The testrunner is working and can be merged.

I also updated the documentation with my experience on getting Spoofax development working in a new Eclipse instance (https://github.com/metaborg/documentation/pull/7).

**Pull request merged**
