### PR TITLE
Hack: invert lightness of colors when Eclipse is using dark theme

### PR DESCRIPTION
**Pull request by mpsijm**
Worth a shot. :stuck_out_tongue: 

I got tired of using Spoofax (in Eclipse) with either a light theme, or with unreadable DSL code in a dark theme, so I thought of a hack that fixed it. No idea whether a hack like this is desirable in the code base of Spoofax, so feel free to reject this PR. I can always keep this patch applied in my local copy of the code base and enjoy a hacked-in dark theme for myself. :innocent: 

How this works: all colors generated by Spoofax at some point need to pass through the `StyleUtils.createColor` method, to turn a `java.awt.Color` into an `org.eclipse.swt.graphics.Color`. In this method, I hacked in a branch that checks whether the current Eclipse theme is dark, and if so, inverts the [_lightness_](https://en.wikipedia.org/wiki/HSL_and_HSV) of this color.

Dark theme detection is done by fetching the color of text in the current Eclipse theme and testing whether it is light or dark (meaning that Eclipse is most likely using a dark or light theme, respectively). This check is performed only when the class is loaded (in the `static` block) and when the theme changes (using a theme listener callback). The result is saved in a `private static boolean` field, so the dark-theme check is almost instant when converting colors.

The inverting of the lightness of the colors uses some code stolen from StackOverflow to convert RGB to HSL and back, and some custom code that inverts the lightness using a fancy formula that I tweaked until it looked good enough. These calculations probably have some overhead, but (1) this overhead is not there in the standard scenario of using Eclipse in a light theme and (2) the small arithmetic overhead when using Eclipse in dark theme is a price I'm willing to pay to make Spoofax usable with a dark theme. :stuck_out_tongue: I haven't benchmarked this, but I didn't notice any difference when using Spoofax on a small test project.

Let me know what you think, and enjoy using Spoofax with a dark theme! :smile: 

EDIT: here's what it looks like: 
image

### CODE REVIEW

**Comment by Apanatshka** [comment]
Sounds clever. Do you think you can do something like this for IntelliJ too? It would be nice to keep behaviour consistent over different IDEs.

**Comment by mpsijm** [comment]
I can try that some time :stuck_out_tongue: The only unknown here would be how to detect whether the IntelliJ theme is dark (hopefully JetBrains' plugin API is a bit better documented than Eclipse's). Other than that, the lightness inversion code can in theory directly be copy/pasted :slightly_smiling_face: (yes, copy/pasted, because this is a hack anyway and having a shared component in Spoofax Core sounds even uglier to me :joy:)

**Comment by mpsijm** [comment]
@Apanatshka I double-checked with @Virtlink, apparently Spoofax-IntelliJ already supports dark mode (or any other theme) by using the colors of the current theme, using [standardized token types](https://macromates.com/manual/en/language_grammars#naming_conventions) (and currently his conversion from Spoofax' token types to these standardized token types is also quite hacky, but better than nothing :stuck_out_tongue:). So my "hack" can remain Eclipse-only for now, and can be removed once Spoofax' color system is rewritten to use this standard.

**Comment by Apanatshka** [comment]
Ok, then I have no further requests. I'm fine with this being merged.

**Comment by Gohla** [comment]
Looks good to me. Not sure what the performance overhead in dark mode is, but that will have to be experimented with. We can always revert this when it is too performance intensive.

**Pull request merged**
